- name: Install custom script helpers
  copy: src={{ item }} dest=/usr/local/bin/{{ item | basename }} mode=0755
  with_fileglob:
    - ../files/*

- name: Install WordPress i18n tools
  shell: "svn co http://develop.svn.wordpress.org/trunk/tools/; ln -s /data/wordpress/htdocs/wordpress src"
  args:
    chdir: /home/vagrant
    creates: /home/vagrant/tools/i18n
