- name: Install custom script helpers 
  copy: src={{ item }} dest=/usr/local/bin/{{ item | basename }} mode=0755
  with_fileglob:
    - ../files/*

- name: Get wp-phptidy for html coding standards
  command: curl -L -o /usr/local/bin/wp-phptidy https://raw.githubusercontent.com/scribu/wp-phptidy/master/wp-phptidy.php

- name: Give wp-phptidy execute permissions
  file:
    path: /usr/local/bin/wp-phptidy
    mode: 0755