---
- name: Install redis
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
  - redis-server
  - php5-redis

- name: Copy the client configuration file
  template: src=redis.j2 dest=/etc/redis/redis.conf
  notify: restart redis

- name: check if Redis is running
  service: name=redis-server state=started

- name: enable redis-server to survive reboot
  service: name=redis-server enabled=yes


