---
- name: Add Nginx PPA from rtcamp
  apt_repository: repo="ppa:rtcamp/nginx" update_cache=yes

- name: Install Nginx
  apt: name=nginx-custom state=present force=yes

- name: Install nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf


- name: Install all nginx config files *.conf
  copy: src={{ item }} dest=/etc/nginx/{{ item | basename }}
  with_fileglob:
  - ../files/*.conf

- name: Install fastcgi_params file
  copy: src=fastcgi_params dest=/etc/nginx/fastcgi_params

- name: Install all default nginx sites
  copy: src={{ item }} dest=/etc/nginx/sites-available/{{ item | basename }}
  with_fileglob:
  - ../files/sites-available/*

- name: Enable all default nginx sites
  file: src=/etc/nginx/sites-available/{{ item | basename }} dest=/etc/nginx/sites-enabled/{{ item | basename }} owner={{ web_user }} group={{ web_user }} state=link
  with_fileglob:
  - ../files/sites-available/*
