---
- name: Add Nginx PPA from rtcamp with pagespeed
  apt_repository: repo="ppa:rtcamp/nginx" update_cache=yes

- name: Install Nginx
  apt: name=nginx-custom state=present force=yes

- name: Install nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Create default server
  template: src=default.conf.j2 dest=/etc/nginx/sites-enabled/default

- name: Create base WordPress config
  template: src=wordpress.conf.j2 dest=/etc/nginx/wordpress.conf

- name: Create base WordPress subdirectory Multisite config
  template: src=multisite_subdirectories.conf.j2 dest=/etc/nginx/multisite_subdirectories.conf

- name: Create fastcgi_params config file
  template: src=fastcgi_params.j2 dest=/etc/nginx/fastcgi_params

- name: Create cache folder
  file: path=/var/cache/nginx/ngx_pagespeed_cache state=directory owner=vagrant group=vagrant