---

- name: Install php xdebug
  apt: name=php5-xdebug state=present force=yes

- name: Install webgrind
  # Origin repo is: https://github.com/jokkedk/webgrind/
  # But it has been abandonded since summer of 2015
  # We are using active fork from alpha0010
  git: repo=https://github.com/alpha0010/webgrind dest=/var/www/webgrind

- name: Add xdebug.ini template
  template: src="20-xdebug.ini.j2"
            dest="/etc/php5/fpm/conf.d/20-xdebug.ini"
  notify: restart web

- name: Install graphviz
  apt: name="{{ item }}" state=present force=yes
  with_items:
  - python
  - graphviz

- name: Symlink dot binary 
  file: src=/usr/bin/dot dest=/usr/local/bin/dot state=link

- name: Use webgrind nginx config
  template: src=webgrind-nginx.conf.j2 dest=/etc/nginx/sites-available/webgrind
  sudo: yes

- name: enable webgrind nginx
  file: src=/etc/nginx/sites-available/webgrind dest=/etc/nginx/sites-enabled/webgrind owner={{ web_user }} group={{ web_user }} state=link
  sudo: yes
  notify: restart web
