---
- name: Add apt bash-completions
  apt: name="bash-completion" state=present force=yes

- name: Get wp-cli bash completions
  get_url:
    url="{{ wp_cli_completion_url }}"
    dest="/usr/share/bash-completion/completions/wp"

- name: Install dummy environment variables
  template: src="container_environment.sh.j2" dest="/etc/container_environment.sh"

- name: Create additions + aliases for .bashrc
  lineinfile:
    dest=/home/vagrant/.bashrc
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^alias mysql', line: "alias mysql='/usr/bin/mysql -u$DB_USER -p$DB_PASSWORD'" }
    - { regexp: '^source /etc/container_environment.sh', line: 'source /etc/container_environment.sh' }

- name: Fix root user - stdin is not a tty - error message when running commands remotely
  lineinfile:
    dest=/root/.profile
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^mesg n', line: "tty -s && mesg n" }
