language: python
os: linux

cache: pip

install:
  - curl -Os https://raw.githubusercontent.com/Seravo/gnitpick/master/gnitpick.py
  - pip install ansible

script:
  # Abort immediately if one step fails
  # https://github.com/travis-ci/travis-ci/issues/1066#issuecomment-32415710
  - set -e

  # Run our custom Git commit checks
  - python3 ./gnitpick.py --target-repository https://github.com/seravo/wp-vagrant.git

  - ansible-playbook --syntax-check -i hosts/development site.yml
