---
- name: "WordPress Server: Install LEMP Stack with PHP 5.6 and MariaDB MySQL + Redis + Devtools."
  hosts: web
  sudo: yes
  remote_user: admin

  roles:
    #Use /data folder for everything project related
    - { role: data-directories, tags: [data-directories] }
    - { role: common, tags: [common] }
    - { role: mariadb, tags: [mariadb] }
    - { role: php, tags: [php] }
    - { role: nginx, tags: [nginx] }
    - { role: xdebug, tags: [xdebug] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: profile, tags: [profile] }
    - { role: redis, tags: [redis] }
    - { role: ruby, tags: [ruby] }
    - { role: nodejs, tags: [nodejs] }
    - { role: phantomjs, tags: [phantomjs] }
    - { role: scripts, tags: [scripts] }
    #Cleanup all files 
    - { role: cleanup, tags: [cleanup] }
