---
- name: "WordPress Server: LEMP Stack with HHVM, PHP, MariaDB for MySQL, Redis and various development tools."
  hosts: web
  sudo: yes
  remote_user: admin

  roles:
    # Use /data folder for everything project related
    - { role: data-directories, tags: [data-directories] }
    - { role: common, tags: [common] }
    - { role: mariadb, tags: [mariadb] }
    - { role: php, tags: [php] }
    # TODO: also add a hhvm-lts package for testing with hhvm 
    - { role: nginx, tags: [nginx] }
    - { role: xdebug, tags: [xdebug] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: profile, tags: [profile] }
    - { role: redis, tags: [redis] }
    - { role: ruby, tags: [ruby] }
    #- { role: libsass, tags: [libsass] } #TODO: this is not finished
    # TODO: add tidy-html5 for html validation for errors
    - { role: adminer, tags: [adminer] }
    #- { role: mailcatcher, tags: [mailcatcher] } #TODO: nginx conf is broken
    - { role: nodejs, tags: [nodejs] }
    - { role: phantomjs, tags: [phantomjs] }
    - { role: scripts, tags: [scripts] }
    - { role: codesniffer, tags: [codesniffer] }
    #Cleanup all files 
    - { role: cleanup, tags: [cleanup] }
