---
- name: Create data directories and set sticky bit for them
  file: path=/data/{{ item }} state=directory owner=vagrant group=vagrant mode=2755
  with_items:
    - log
    - db
    - wordpress
    - home
    - redis

- name: 777 for log directory
  file: path=/data/log mode=2777 owner=vagrant group=vagrant