- name: Stop Docker image as it should not be running in packaged box
  shell: /usr/sbin/sc stop || true

- name: Remove Docker image so a new one is created on next startup
  shell: /usr/sbin/sc remove || true

- name: Remove non-essential packages
  apt:
    pkg: "{{ item }}"
    state: absent
    autoremove: yes
    autoclean: yes
    purge: yes
  with_items:
    - gcc
    - gcc-5
    - gcc-7-base
    - python2.7
    - lxc-common
    - lxd
    - lxd-client
    - make
    - telnet
    - strace
    - snapd
    - pollinate
    - ntfs-3g
    - fakeroot
    - eatmydata
    - python3-twisted
    - lvm2
    - perl-modules-5.26
    - vim
    - vim-runtime
    - iso-codes
    - btrfs-progs

- name: Remove docs and locales very unlikely to be needed
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - /usr/share/locale
    - /usr/share/doc
    - /usr/share/man
    - /usr/share/i18n

- name: Remove temporary content
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - /var/cache/apt/archives
    - /var/cache/apt/pkgcache.bin
    - /var/cache/apt/srcpkgcache.bin
    - /var/lib/apt/lists
    - /root/.composer
    - /root/.npm
    - /root/.gem

- name: Restore essential directories
  file:
    state: directory
    dest: "{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - /var/cache/apt/archives
    - /var/lib/apt/lists

- name: Install cleanup script
  copy:
    src: cleanup.sh
    dest: /cleanup.sh
    mode: 0700
    owner: root
    group: root

- name: Run cleanup script to save disk space
  shell: "/cleanup.sh"
