---
- name: Add Nodejs ppa
  apt_repository: repo="ppa:chris-lea/node.js" update_cache=yes

- name: Install Nodejs
  apt: name=nodejs state=present force=yes

- name: Install NPM Packages
  npm: name="{{ item }}" global=yes state=latest
  with_items:
    #Nice terminal editor
    - slap
    # Dependency handling
    - bower
    # Workflow
    - gulp
    - gulp-sass
    - gulp-coffee
    - gulp-bower
    - gulp-util
    - gulp-watch
    - gulper

- name: Use NPM bash-completion
  file: src=/usr/lib/node_modules/npm/lib/utils/completion.sh dest=/usr/share/bash-completion/completions/npm state=link
