---
- name: Install Seravo fork of wetty 
  git: repo=https://github.com/seravo/wetty dest={{wetty_install_path}}

- name: Install npm packages
  command: "npm install"
  args:
    chdir: {{wetty_install_path}}
  sudo: yes

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: Start example Node.js app
  command: forever start "{{wetty_install_path}}/app.js"
  when: "forever_list.stdout.find('{{wetty_install_path}}') == -1"

- name: use wetty nginx config
  template: src=wetty-nginx.conf.j2 dest=/etc/nginx/sites-available/wetty

- name: enable wetty nginx
  file: src=/etc/nginx/sites-available/wetty dest=/etc/nginx/sites-enabled/wetty owner={{ web_user }} group={{ web_user }} state=link

