---
- name: Install Seravo fork of wetty 
  git: repo=https://github.com/seravo/wetty dest={{wetty_install_path}}

- name: Change ownership of wetty to web_user
  - file: path={{wetty_install_path}} owner={{ web_user }} group={{ web_user }}

- name: Install npm packages
  command: "npm install"
  args:
    chdir: "{{wetty_install_path}}"
  sudo: yes

- name: Add wetty into init scripts
  template: src=wetty-init.conf.j2 dest=/etc/init/wetty.conf

- name: use wetty nginx config
  template: src=wetty-nginx.conf.j2 dest=/etc/nginx/sites-available/wetty

- name: enable wetty nginx
  file: src=/etc/nginx/sites-available/wetty dest=/etc/nginx/sites-enabled/wetty owner={{ web_user }} group={{ web_user }} state=link

