# Most of the config is in nginx default server and gulpfile.js of seravo/wordpress
# Browsersync opens 2 ports: 1337 (proxying) and 1338 (admin-panel)
# 1337 is used as main middleware into wordpress 
# 1338 is mapped under domain browsersync.*

- name: Install NPM Packages
  npm: name="{{ item }}" global=yes state=latest
  with_items:
    - browser-sync

- name: use nginx config
  template: src=browsersync-nginx.conf.j2 dest=/etc/nginx/sites-available/browsersync

- name: enable nginx config
  file: src=/etc/nginx/sites-available/browsersync dest=/etc/nginx/sites-enabled/browsersync owner={{ web_user }} group={{ web_user }} state=link
