---
- name: Update Apt
  apt: update_cache=yes

- name: Checking essentials
  apt: name="{{ item }}" state=present
  with_items:
  - python-software-properties
  - python-pycurl
  - build-essential
  - ca-certificates
  - python-mysqldb
  - curl
  - git-core
  - subversion
  - avahi-daemon
  - bash-completion
  - vim

- name: Add DigiCertHighAssuranceEVRootCA-2.crt to trusted since that's what github uses
  copy: src=DigiCertHighAssuranceEVRootCA-2.crt dest=/usr/local/share/ca-certificates/DigiCertHighAssuranceEVRootCA-2.crt

- name: Update root ca-certificates
  command: update-ca-certificates