---
- name: Install essentials
  apt: name="{{ item }}" state=present update_cache=true
  with_items:
  - software-properties-common
  - python-pycurl
  - build-essential
  - ca-certificates
  - python-mysqldb
  - curl
  - git
  - subversion
  - avahi-daemon
  - bash-completion
  - vim
  - htop
  - graphicsmagick
  - apt-transport-https
  - pv

- name: Add DigiCertHighAssuranceEVRootCA-2.crt to trusted since that's what github uses
  copy: src=DigiCertHighAssuranceEVRootCA-2.crt dest=/usr/local/share/ca-certificates/DigiCertHighAssuranceEVRootCA-2.crt

- name: Update root ca-certificates
  command: update-ca-certificates

- name: Customize message of the day
  lineinfile: dest=/etc/motd line={{ item }} create=yes line="WordPress Developer Documentation https://seravo.com/docs/"

- name: Use vagrant's insecure public key
  authorized_key: user=vagrant key="{{ item }}"
  with_file:
  - vagrant.pub
