---
# Update basebox, we don't known when it was build
- name: upgrade the system
  apt:
    upgrade: safe
    update_cache: yes

- name: install dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - ca-certificates # for SSL certs
    - localepurge     # strip unnecessary locales => save disk space
    - curl            # download files...
    - python-pip      # needed for ansible pip tasks
    - unattended-upgrades # do automatic updates for the VM
    - docker.io
    - ifupdown

# this allows us to SSH directly into the Docker container on start
# source: <https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant>
- name: add vagrant private key
  copy:
    src: vagrant.key
    dest: /home/vagrant/.ssh/id_rsa_vagrant
    mode: 0600
    owner: vagrant
    group: vagrant

# pull docker image, create container
- name: copy helper script
  copy:
    src: sc.sh
    dest: /usr/sbin/sc
    mode: 0755
    owner: root
    group: root

- name: create seravo dir
  file:
    dest: /usr/share/seravo
    state: directory
    mode: 0755
    owner: root
    group: root

- name: configure Seravo environment
  copy:
    src: env
    dest: /usr/share/seravo/env
    mode: 0644
    owner: root
    group: root

- name: create data placeholder
  file:
    dest: /data/wordpress
    state: directory
    mode: 0755
    owner: root
    group: root

# Create flag file: do not jump to docker if file exists
- name: create flag file for docker shell
  lineinfile:
    regexp: '^1'
    dest: /data/wordpress/.nodocker
    mode: 0644
    owner: vagrant
    group: root
    create: yes
    line: '1'

# Allow user to choose wheter she likes to enter Docker or host VM
# if ~/.nodocker exists, user won't be forwarded to container
- name: add check for flag file
  lineinfile:
    state: present
    regexp: 'exec /usr/bin/sc shell$'
    line: '[ ! -e "/data/wordpress/.nodocker" ] && exec /usr/sbin/sc shell'
    dest: '{{ item }}/.bashrc'
  with_items:
    - /home/vagrant
    - /root

- name: create noop-wrappers for obsolete commands
  copy:
    src: wp-wrapper-noop
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - composer
    - wp
    - wp-activate-git-hooks
    - wp-generate-ssl
    - wp-restart-nginx
    - wp-use-asset-proxy
    - wp-vagrant-activation
    - wp-pull-production-db
    - wp-vagrant-dump-db
    - wp-vagrant-import-db
    - wp-watch-logs

# Delay docker start vagrant finishes mounting /data before docker
# mounts /data:/data
- name: create directory structure for systemd override
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: add delay helper
  copy:
    src: wait-mounts.sh
    dest: /usr/local/sbin/wait-mounts.sh
    mode: 0755
    owner: root
    group: root

- name: delay docker start
  copy:
    src: "{{ item }}.conf"
    dest: "/etc/systemd/system/docker.service.d/{{ item }}.conf"
    mode: 0644
    owner: root
    group: root
  with_items:
      - delay

# Keep the Docker host motd silent and rely on the motd emitted by the container
- name: Clean away excess motd messages
  file:
    path: "/etc/{{ item }}"
    state: absent
  with_items:
      - update-motd.d
      - motd

- name: Add Seravo WordPress service
  copy:
    src: seravo-wordpress.service
    dest: /etc/systemd/system/seravo-wordpress.service
    mode: 0644
    owner: root
    group: root

- name: configure systemd services
  systemd:
    daemon_reload: yes
    enabled: yes
    state: stopped
    name: seravo-wordpress

- name: pull docker image and create container
  shell: /usr/sbin/sc pull

# create file that contains build timestamp
- name: create build timestamp file
  shell: echo "vagrant-$(date --iso-8601=ns)" >/buildtime
