---
- name: Add PHP 5.6 PPA
  apt_repository: repo="ppa:ondrej/php5-5.6" update_cache=yes

- name: Install PHP 5.6
  apt: name="{{ item }}" state=present force=yes
  with_items:
  - php5-common
  - php5-fpm
  - php5-mysqlnd
  - php5-xmlrpc
  - php5-mcrypt
  - php5-curl
  - php5-gd
  - php5-cli
  - php-pear
  - php5-dev
  - php5-imap
  - phpunit

- name: Create socket directory
  file: path={{php_fpm_socket_dir}} state=directory owner=vagrant group=vagrant

- name: Update php5-fpm upstart script
  template:
    src: php5-fpm-upstart.conf.j2
    dest: /etc/init/php5-fpm.conf

- name: Start php5-fpm service
  service: name=php5-fpm state=restarted enabled=true

- name: Disable default pool
  command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled creates=/etc/php5/fpm/pool.d/www.disabled
  when: disable_default_pool
  notify: restart php-fpm

- name: Add php.ini template
  template: src="php.ini.j2"
            dest="/etc/php5/fpm/php.ini"
  notify: restart php-fpm

- name: Add php-fpm.conf template
  template: src="php-fpm.conf.j2"
            dest="/etc/php5/fpm/php-fpm.conf"
  notify: restart php-fpm
