---
- name: Prevent Apache and PHP 7.1 from being installed at any time
  copy:
    src: php-blocks
    dest: /etc/apt/preferences.d/

- name: Add ondrej/php repo with PHP5 and PHP7
  apt_repository: repo="ppa:ondrej/php"

- name: Install PHP 5.6 and 7.0
  apt: name="{{ item }}" state=present force=yes update_cache=yes
  with_items:
  - php5.6-common
  - php5.6-fpm
  - php5.6-mysql
  - php5.6-curl
  - php5.6-gd
  - php5.6-mcrypt
  - php5.6-memcache
  - php5.6-tidy
  - php5.6-xmlrpc
  - php5.6-xsl
  - php5.6-redis
  - php5.6-mbstring
  - php5.6-soap
  - php5.6-zip
  - php5.6-imagick
  - php5.6-dev
  - php5.6-imap
  - php5.6-xdebug
  - php7.0-common
  - php7.0-fpm
  - php7.0-mysql
  - php7.0-curl
  - php7.0-gd
  - php7.0-mcrypt
  - php7.0-memcache
  - php7.0-tidy
  - php7.0-xmlrpc
  - php7.0-xsl
  - php7.0-redis
  - php7.0-mbstring
  - php7.0-soap
  - php7.0-zip
  - php7.0-imagick
  - php7.0-dev
  - php7.0-imap
  - php7.0-xdebug
  - php7.1-common
  - php7.1-fpm
  - php7.1-mysql
  - php7.1-curl
  - php7.1-gd
  - php7.1-mcrypt
  - php7.1-memcache
  - php7.1-tidy
  - php7.1-xmlrpc
  - php7.1-xsl
  - php7.1-redis
  - php7.1-mbstring
  - php7.1-soap
  - php7.1-zip
  - php7.1-imagick
  - php7.1-dev
  - php7.1-imap
  - php7.1-xdebug
  - php-pear
  - phpunit

- name: Set PHP 7.0 as the default (in auto mode 7.1 would be chosen)
  shell: update-alternatives --set php /usr/bin/php7.0

- name: Create socket directories
  file: path={{item}} state=directory owner=vagrant group=vagrant
  with_items:
    - /var/run/php5-fpm/
    - /var/run/php7-fpm/
    - /var/run/php7.1-fpm/

- name: Stop any running php processes after the install
  service: name={{item}} state=stopped
  with_items:
    - php5.6-fpm
    - php7.0-fpm
    - php7.1-fpm
  ignore_errors: yes # The services might already be deleted

- name: Remove bundled default upstart scripts
  file: name={{item}} state=absent
  with_items:
    - /etc/init.d/php5.6-fpm
    - /etc/init/php5.6-fpm.conf
    - /etc/init.d/php7.0-fpm
    - /etc/init/php7.0-fpm.conf
    - /etc/init.d/php7.1-fpm
    - /etc/init/php7.1-fpm.conf

- name: Update php5-fpm upstart script
  template:
    src: php5-fpm-upstart.conf.j2
    dest: /etc/init/php5-fpm.conf

- name: Update php7-fpm upstart script
  template:
    src: php7-fpm-upstart.conf.j2
    dest: /etc/init/php7-fpm.conf

- name: Update php7.1-fpm upstart script
  template:
    src: php7.1-fpm-upstart.conf.j2
    dest: /etc/init/php7.1-fpm.conf

- name: Start php5-fpm service
  service: name=php5-fpm state=restarted enabled=true

- name: Start php7-fpm service
  service: name=php7-fpm state=restarted enabled=true

- name: Start php7.1-fpm service
  service: name=php7.1-fpm state=restarted enabled=true

- name: Add php.ini template for php5-fpm
  template: src="php5.6/php.ini.j2"
            dest="/etc/php/5.6/fpm/php.ini"
  notify: restart php5-fpm

- name: Add php.ini template for php7-fpm
  template: src="php7.0/php.ini.j2"
            dest="/etc/php/7.0/fpm/php.ini"
  notify: restart php7-fpm

- name: Add php.ini template for php7.1-fpm
  template: src="php7.1/php.ini.j2"
            dest="/etc/php/7.1/fpm/php.ini"
  notify: restart php7.1-fpm

- name: Add php-fpm.conf template for php5-fpm
  template: src="php5.6/php-fpm.conf.j2"
            dest="/etc/php/5.6/fpm/php-fpm.conf"
  notify: restart php5-fpm

- name: Add php-fpm.conf template for php7-fpm
  template: src="php7.0/php-fpm.conf.j2"
            dest="/etc/php/7.0/fpm/php-fpm.conf"
  notify: restart php7-fpm

- name: Add php-fpm.conf template for php7.1-fpm
  template: src="php7.1/php-fpm.conf.j2"
            dest="/etc/php/7.1/fpm/php-fpm.conf"
  notify: restart php7.1-fpm
